export enum ExpenseType {
  GENERICA = 'GENÉRICA',
  REFEICAO = 'REFEIÇÃO',
  ESTACIONAMENTO = 'ESTACIONAMENTO',
  COMBUSTIVEL = 'COMBUSTÍVEL',
  PORTAGENS = 'PORTAGENS',
  ALOJAMENTO = 'ALOJAMENTO',
  TAXI = 'TÁXI',
  BILHETES = 'BILHETES',
  OUTROS = 'OUTROS',
}
